language: python
python:
- '3.5'
branches:
  only:
  - master
  - develop
install:
- pip install -r requirements.txt
script:
- printenv
deploy:
  provider: pypi
  user: alkov.pro
  password:
    secure: "VcxcBOqgChPSjamYGohdJuHSeeQWo1x8YevKg84Goek+lqFcXVrsb/f3UnJblJHRj9RjvPmb20VsfWV5FoTh9QcXnQWzHR3ZQv7SjjFhpjsyrZ3YHMsxpJS8yRRAKiuRxtnwHM7Zl5R6bOKgkCpwzVCZD1GcCXqNCKNikDJSvPJ71NeDvLtgUhCOJUOAaUy4oK3Ofj4iOaOeFfp1LEw7ZwTA4d4IkM97cl1TIX5/VnLvJqeNBlYzCyOvhyCyB3cTncrNHx3K8pmpdEVitBEsaLKQgKqPlAYRmZz3QvrTs2cUW+9/ciwfscOvlebyi04skLjLLRzRSfEbwG/Sz8JPqOZlnXYtdHgi2Yx02yXj2PQNUvmKwXGEQJNL95zU+7SVNOkmd48J3IQUPuW2i37hFDmkCROZpts2Xm77k9f6cbjaJH3lPKyFtQgvhydtHsd0WARhNlg3QywaEYeP8+oz9GhsdbaGTUYDoYthKZrprk8EDzxKGs+MRjQOv6yZyqNrvvhxgHF2wAIFCX4goGu37mQmIvIROkVW0HtRaNJI7hIZshoBy8GvPbNfaZmo/al+kNMS2tB4Dy9B4LLu0RMvA4Xo57OTyL64DZJSGbSytoXLIN4S5KrxxKmjxLV/A+2nQ6bCgi/bmI9mQZ1MDB4iNoVWFnfwpSw2suSJWjUWJyI="
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    branch: master
