language: python
python:
- '3.5'
branches:
  only:
  - master
  - develop
install:
- pip install -r requirements.txt
script:
- printenv
deploy:
  provider: pypi
  user: alkov.pro
  password:
    secure: "WFSLP7jgZmq931mOMacWd5JniAriufBJZBoAJzvPgNhUzW7hdTe6wZlHIkNqvvrnHKco4BT2A4LoD//qbyYtS/BRdNr2WFKt+KZN/aUVNbwfpodqsaFH74PrZvppnL60cP0sFabZNtLI5/JxhA36XdH6PfmTqMc4EEGUA8+EBExya++bTE6dVR19YvY3dep7fC5RyHNGV24L8X77jUA0z/0Wp55CqzWm64CHEzJLTkc3F7KBKOJwY2dnM9pRAl6FCepyr3F0mzFGjvcb88Wrhv67GA1X9ICq5tnPszEo4Q1ImX5WnxBqepmJjdW2zx/By3jwam0sytQcWgxbM+KqSdzFHbsNL+sjIqWMdefjX4RXnpepu9Xxf2DlrfeBQz9rmq8rcaNgIs14OEQebkb3bJXv+jaFFFQmSxjMzF0yjCwzOyDM62Me7jqYFfui+7sMnDraza4cqDjBtrWQ9vPaq8aaPugdlNJFr85Bk7S2Isuw41VlEpOhxviihlU68lRbelgu2La9OFLq3ZLeDKyRElbNkbekxUFz5t9aGoGejqYJybSvQZjM+/qv9Pv52Jwqgy7j1nO9LymW2pBFGzhZh2o7yjo55yhf1WumVNNqxZ7VGsRohcJEIVuLR+wTk9/06RzrXuJ+pK6Lsfmft4zZFpygfSrZmoc2u8izSW7esh0="
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    branch: master
